namespace: bitwarden
name: secrets
version: 1.0.0
readme: README.md
authors:
  - Bitwarden <hello@bitwarden.com>
description: This is a Collection of the Bitwarden Secrets Manager lookup plugin.
license:
  - GPL-3.0-or-later
tags:
  - access
  - account
  - bitwarden
  - credential
  - identity
  - secret
  - security
  - privileged
  - vault
  - devops
repository: https://github.com/bitwarden/sm-ansible
documentation: https://bitwarden.com/help
homepage: https://bitwarden.com/products/secrets-manager
issues: https://github.com/bitwarden/sm-ansible/issues
build_ignore:
  - .editorconfig
  - .env
  - .git
  - .gitignore
  - .gitattributes
  - .github
  - .husky
  - .idea
  - .vagrant
  - .venv
  - .vscode
  - __pycache__
  - ansible.cfg
  - package.json
  - package-lock.json
  - tests
