---
name: Test Ansible Playbooks

on:
  workflow_dispatch:
    inputs:
      ansible_branch:
        description: "Branch to test"
        required: true
        default: "main"
      sdk_branch:
        description: "Branch to use for bitwarden/sdk"
        required: true
        default: "main"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.inputs.ansible_branch || github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.9"

      - name: Install Ansible
        run: |
          python -m venv ${{ github.workspace }}/.venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      # TODO: Replace these steps with a simple `pip install bitwarden_sdk`
      #   once the package is published to PyPI
      - name: Clone bitwarden/sdk
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: bitwarden/sdk
          ref: main
          path: sdk

      - name: Download Python SDK
        uses: bitwarden/gh-actions/download-artifacts@main
        with:
          workflow: build-python-wheels.yml
          workflow_conclusion: success
          path: dist
          branch: ${{ github.event.inputs.sdk_branch || 'main' }}

      - name: Install bitwarden/sdk
        working-directory: sdk
        run: |
          source ${{ github.workspace }}/.venv/bin/activate
          pip install --no-index --find-links=dist bitwarden_sdk

      - name: Lint
        run: |
          source ${{ github.workspace }}/.venv/bin/activate
          ansible-playbook --syntax-check examples/*.yml
          ansible-lint examples/*.yml

      - name: Run Playbooks
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: |
          source ${{ github.workspace }}/.venv/bin/activate
          ansible-playbook examples/test.yml # just run this playbook for now
