---
name: Test Ansible Playbooks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test"
        required: true
        default: "main"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.9"

      - name: Install Ansible
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install ansible

      # TODO: Replace these steps with a simple `pip install bitwarden_sdk`
      #   once the package is published to PyPI.
      - name: Clone bitwarden/sdk
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: bitwarden/sdk
          ref: SM-989-create-build-and-publish-pipelines-for-the-python-language-wrapper
          path: sdk

      - name: Generate schemas.py
        working-directory: sdk
        run: |
          npm install
          npm run schemas

      - name: Install bitwarden/sdk
        working-directory: sdk/languages/python
        run: |
          pip install maturin[patchelf]
          maturin develop

      - name: Lint
        run: |
          ansible-playbook --syntax-check examples/*.yml
          ansible-lint examples/*.yml

      - name: Run Playbooks
        run: |
          ansible-playbook examples/test.yml # just run this playbook for now
