name: Version Bump
run-name: Version Bump - v${{ inputs.version_number }}

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "New version (example: '1.1.0')"
        required: true

jobs:
  bump_version:
    name: "Bump Version to v${{ inputs.version_number }}"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    env:
      _VERSION: ${{ inputs.version_number }}
    steps:
      - name: Log in to Azure
        uses: bitwarden/gh-actions/azure-login@main
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Retrieve secrets
        id: retrieve-secret
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: gh-org-bitwarden
          secrets: "BW-GHAPP-ID,BW-GHAPP-KEY"

      - name: Log out from Azure
        uses: bitwarden/gh-actions/azure-logout@main

      - name: Generate GH App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ steps.retrieve-secret.outputs.BW-GHAPP-ID }}
          private-key: ${{ steps.retrieve-secret.outputs.BW-GHAPP-KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Version Branch
        id: create-branch
        run: |
          NAME=version_bump_${GITHUB_REF_NAME}_${_VERSION}
          git switch -c "$NAME"
          git push -u origin "$NAME"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      ########################
      # VERSION BUMP SECTION #
      ########################

      - name: Bump Version
        run: yq -i ".version = \"${_VERSION}\"" galaxy.yml

      ############################
      # VERSION BUMP SECTION END #
      ############################

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_to_commit=TRUE" >> "$GITHUB_OUTPUT"
          else
            echo "changes_to_commit=FALSE" >> "$GITHUB_OUTPUT"
            echo "No changes to commit!"
          fi

      - name: Run prettier
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        run: |
          npm ci
          npm run prettier

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        run: git commit -m "Bumped version to ${_VERSION}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
        run: git push -u origin "$PR_BRANCH"

      - name: Create Version PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        id: create-pr
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
          TITLE: "Bump version to ${{ inputs.version_number }}"
        run: |
          PR_URL=$(gh pr create --title "$TITLE" \
            --base "main" \
            --head "$PR_BRANCH" \
            --label "version update" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated version bump to ${_VERSION}")
          echo "pr_number=${PR_URL##*/}" >> "$GITHUB_OUTPUT"

      - name: Approve PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr review "$PR_NUMBER" --approve

      - name: Merge PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr merge "$PR_NUMBER" --squash --auto --delete-branch
